<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0fedb4cd-b84d-49e0-b20a-189107d2d641</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sauce_labs_backpack</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#item_4_title_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Sauce Labs Backpack')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sauce Labs Backpack</value>
        <webElementGuid>8e274b65-4ae1-4688-a2fc-08f2411f185d</webElementGuid>
    </webElementProperties>
</WebElementEntity>