<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b19291cc-5f70-4ea8-917d-12e485cd0791</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_place_an_order</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-action\ btn-anim"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Place an order')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Place an order</value>
        <webElementGuid>fdf7ca03-c02d-409b-9bf9-90122b9276bf</webElementGuid>
    </webElementProperties>
</WebElementEntity>